### ISSUE TITLE
Please update fxqrl on addons.mozilla.org

### ISSUE THREAD

**Issue by QJKX** [xeonchen/fxqrl#7]
Love the extension.

A small problem - sometimes barcodes don't scan when the page background is black, because the "quiet zone"/margin is missing.
https://en.wikipedia.org/wiki/QR_code#/media/File:QR_Code_Structure_Example_3.svg

You've already fixed this in fdff5ec9154405420505a3be2cdb9886090b95b0.

**Comment by xeonchen** [comment]
Thank you for reporting this, unfortunately I don't have time to handle this for a while. I'll fix this in the near future. Sorry for your inconvenience.

**Comment by xeonchen** [comment]
Add-on updated
